<a href="https://colab.research.google.com/github/kahakashanashraf/machine-learning/blob/main/Copy_of_Naive_Bayes_Sample_Code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Importing the packages
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import sklearn


In [ ]:
# Importing the dataset
dataset = pd.read_csv('/content/collegePlace.csv')
dataset.tail(5)

Age Gender  ... HistoryOfBacklogs  PlacedOrNot
2961   23   Male  ...                 0            0
2962   23   Male  ...                 0            0
2963   22   Male  ...                 0            0
2964   22   Male  ...                 0            0
2965   23   Male  ...                 0            1

[5 rows x 8 columns]

In [ ]:
# if your dataset contains missing value, check which column has missing values
dataset.isnull().sum()

Age                  0
Gender               0
Stream               0
Internships          0
CGPA                 0
Hostel               0
HistoryOfBacklogs    0
PlacedOrNot          0
dtype: int64

In [ ]:
# if your dataset contains missing value, remove those missing values
dataset.dropna(inplace=True)

In [ ]:
li = [1, 2, 3, 'february', 5, 6, 'march']
li[-3]

5

In [ ]:
## encoding the categorical features
from sklearn import preprocessing

col_cat = ['Gender','Stream']

lab_en= preprocessing.LabelEncoder()

for c in col_cat:
    dataset[c]= lab_en.fit_transform(dataset[c])

dataset.head()

Age  Gender  Stream  ...  Hostel  HistoryOfBacklogs  PlacedOrNot
0   22       1       3  ...       1                  1            1
1   21       0       1  ...       1                  1            1
2   22       0       4  ...       0                  0            1
3   21       1       4  ...       0                  1            1
4   22       1       5  ...       1                  0            1

[5 rows x 8 columns]

In [ ]:
## correlation values of features with target label
corr_col = np.abs(dataset.corr()['PlacedOrNot']).sort_values(ascending=False)
corr_col = corr_col.rename_axis('Col').reset_index(name='Correlation')
corr_col

Col  Correlation
0        PlacedOrNot     1.000000
1               CGPA     0.588648
2        Internships     0.179334
3                Age     0.046943
4             Hostel     0.038182
5  HistoryOfBacklogs     0.022337
6             Gender     0.006705
7             Stream     0.001341

In [ ]:
## features and target label
X = dataset.iloc[:, [0,3,4,5]].values
y = dataset.iloc[:, -1].values

In [ ]:
X[:4]

array([[22,  1,  8,  1],
       [21,  0,  7,  1],
       [22,  1,  6,  0],
       [21,  0,  8,  0]])

In [ ]:
## train-test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0, shuffle= True)

In [ ]:
##scaling the features
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [ ]:
y_pred  =  classifier.predict(X_test)
y_pred, y_test


(array([1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1,
        1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1,
        0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0,
        0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
        0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0,
        1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1,
        0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1,
        1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1,
        1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1,
        0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
        1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0,
        1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
        1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test, y_pred)
ac = accuracy_score(y_test,y_pred)

In [ ]:
print("Confusion Matrix\n", cm, "\n Accuracy:", ac)

Confusion Matrix
 [[233  26]
 [ 63 272]] 
 Accuracy: 0.8501683501683501
