<a href="https://colab.research.google.com/github/kahakashanashraf/machine-learning/blob/main/Errorrate.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Importing the packages
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import sklearn

In [ ]:
# Importing the dataset
dataset = pd.read_csv('/content/Fish.csv')
dataset.tail(5)

FileNotFoundError: ignored

In [ ]:
# if your dataset contains missing value, check which column has missing values
dataset.isnull().sum()

Species    0
Weight     0
Length1    0
Length2    0
Length3    0
Height     0
Width      0
dtype: int64

In [ ]:
## encoding the categorical features
from sklearn import preprocessing

col_cat = ['Species']

lab_en= preprocessing.LabelEncoder()

for c in col_cat:
    dataset[c]= lab_en.fit_transform(dataset[c])

dataset.head()

Species  Weight  Length1  Length2  Length3   Height   Width
0        0   242.0     23.2     25.4     30.0  11.5200  4.0200
1        0   290.0     24.0     26.3     31.2  12.4800  4.3056
2        0   340.0     23.9     26.5     31.1  12.3778  4.6961
3        0   363.0     26.3     29.0     33.5  12.7300  4.4555
4        0   430.0     26.5     29.0     34.0  12.4440  5.1340

In [ ]:
## correlation values of features with target label
corr_col = np.abs(dataset.corr()['Weight']).sort_values(ascending=False)
corr_col = corr_col.rename_axis('Col').reset_index(name='Correlation')
corr_col

Col  Correlation
0   Weight     1.000000
1  Length3     0.923044
2  Length2     0.918618
3  Length1     0.915712
4    Width     0.886507
5   Height     0.724345
6  Species     0.312960

In [ ]:
## features and target label
X = dataset.iloc[:, [0,2,3,4,5,6]].values
y = dataset.iloc[:, 1].values

In [ ]:
X[:3]

array([[ 0.    , 23.2   , 25.4   , 30.    , 11.52  ,  4.02  ],
       [ 0.    , 24.    , 26.3   , 31.2   , 12.48  ,  4.3056],
       [ 0.    , 23.9   , 26.5   , 31.1   , 12.3778,  4.6961]])

In [ ]:
## train-test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0, shuffle= True)


In [ ]:
##scaling the features
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
from sklearn.neural_network import MLPRegressor
from sklearn.metrics import mean_squared_error

In [ ]:
reg = MLPRegressor(hidden_layer_sizes=(1024),activation="relu" ,random_state=1, max_iter=10000).fit(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10000) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


In [ ]:
y_pred  =  reg.predict(X_test)
y_pred, y_test


(array([ 379.68269179,  112.48726813,  156.75584328,  145.49055348,
         612.73767642,  900.07352289,  803.06766914,  328.91742224,
        1021.75007049,  121.56398002,  220.57720618,  526.54269981,
        1019.52584482, 1160.18529279,   47.00531221,   91.43206601,
         140.11665329, 1510.33916797,  136.06056524,  740.59485794,
          53.68237638,  404.9840782 ,  136.29729761, 1700.56713248,
          82.72289032,  458.41489613,  719.49035332,  285.07830441,
         898.33915119,    7.97251959,  549.95844395,  130.57192517]),
 array([ 390. ,    0. ,  170. ,  160. ,  556. ,  900. ,  800. ,  300. ,
         975. ,  115. ,  200. ,  456. , 1000. , 1000. ,   60. ,   78. ,
         145. , 1600. ,  130. ,  720. ,   55. ,  390. ,  120. , 1650. ,
          90. ,  450. ,  700. ,  270. ,  850. ,    9.7,  650. ,  110. ]))

In [ ]:
print("Error rate ", mean_squared_error(y_pred, y_test))

Error rate  2384.4886192868717
